apiVersion: v1
kind: Service
metadata:
  name: cortex-service
  namespace: cortex
spec:
  selector:
    app: cortex
  ports:
  - protocol: TCP
    port: 6001
    targetPort: 6001
  type: ClusterIP






























